name: Bump Homebrew formula

on:
  push:
    tags:
      - 'v*'

jobs:
  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: rebase-stack
          homebrew-tap: wass88/homebrew-rebase-stack
          base-branch: main
        env:
          COMMITTER_TOKEN: ${{ secrets.PAT }}

